export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Cart } from "./Cart";
export { default as Detail } from "./Detail";
export { default as Wishlist } from "./Wishlist";
export { default as ErrorPage } from "./404";
export { default as SalePage } from "./Sales";
export { default as Search } from "./Search";
export { default as Category } from "./Category";
